# 1 {#sec-01}

You decide not to attempt surgery, it sounds too dangerous. You drive yourself back to your apartment and fashion yourself a fake nose out of putty. It looks all right, almost good enough to pass for a real nose! You decide that you’d like to try going out in public with the new nose, so you contact Dr. Kartoffel to see if he’d like to play tennis with you. He accepts, and you head out to the tennis courts. 

It's a baking hot summer’s day in mid-July, and Dr. Kartoffel is ahead by at least ten points, not that you really care. This was mostly just a way to convince yourself to get out of your shabby, candle-filled apartment, and you don’t like tennis much, but you had spare racquets (given to you by your mother as a late birthday present last August, you never had the heart to throw them away) and decided to give it a try. However, the heat of the sun and of your face in embarrassment at the loss, and the sweat of exercise, have loosened your false nose. It starts to fall off as Dr. Kartoffel is serving and you try to mush it onto your face while also trying to bounce the tennis ball back to him. You fall onto the floor from trying to do multiple things with multiple hands and lie there until Dr. Kartoffel gives up trying to revive you. 

You trudge dejectedly back to your house as the sun is setting, painting the sky with rather dull colors because of course that’s the way your day is going. Your nose is mashed in and has little concrete flecks embedded in it. You try desperately to repair it, but you know that it is broken forever. Sadly, you take the putty off of what used to be your nose and stare into your small, cracked mirror at the mutilated mess of your face.

You stay in the apartment for the rest of your life, haunted by your decisions and lack of a nose, surrounded by the candles that were your undoing.

x