# 5 {#sec-05}

You start to sprint down the street. You don’t trust the spaceship. It seems…ominous. You’d really like to get away from it and on with your day, but as you run down the road, suddenly a bright chartreuse light shines above you and you stop making forward progress, instead slowly rising into the air!

You make comical running motions in the air, trying to get away from the ship and the light. As you slowly rise higher and higher, you give up on the air-running and try to swim away from the light. As you desperately make swimming motions with your arms and kick around with your legs, you glance upwards to see that the light is coming from the ship, through the portal that you spotted earlier, which has spiraled open. 

You abandon the swimming motions as the light draws you ever upwards, closer and closer to the ship. Instead, you wildly flail around in a last-ditch effort to escape the pull of the bright chartreuse light. Despite your attempts, your rise accelerates from the slow ascent of seconds before, and you are flung upwards into the alien spacecraft. The circular port shuts behind you, spiraling closed without a sound.

The interior of the craft, like the outside, is uniformly gray. The ceilings, like the exterior, are completely covered in neat grey wiring. There’s a grey door on one of the walls nearest to you, but you can see no doorknob.
As you take in your surroundings, there comes a pneumatic hiss and the door lifts out of the wall and shifts to the side, letting in… some spheres. They’re identical, all the same color grey as all the rest of the ship. They bob up and down as they travel through the air towards you. You suppose that these strangely monochrome spheres must have built the rickety spacecraft whose floor on which you are currently slumped. 

The alien spheres, as a group, bob closer and closer as they approach you. What should you do? 

If you try to talk to them and be friendly, turn to @sec-48.

If you scream, turn to @sec-11.
 
