---
title: "6"
---

You tell him no. You don’t really feel like wading through a bunch of other people’s trash, and just to find one duck. He could probably find another identical one at a chain toy store somewhere and be just as happy with it. You tell him as much.

He seems completely heartbroken and falls at your feet, sobbing about his plight. He wails about his misfortune; about how desperate he is. He weeps about how his poor duck is in that sewage plant all alone and scared in the dark, shivering from the cold. How sad it must be, how desperate, how hungry! How it needs for someone to save it, but you, a coward, oh how cowardly you are, you have refused, how cold-hearted you are, how foolish, if you could show some sympathy, oh please some sympathy, sympathy for a poor duck, a poor duck lost and alone, a poor lost rubber duck desperately missed, so sad, so despondent, if not for you, life would be filled with nothing but joy but you have refused! Oh! Refused and there is nothing he can do about it, nothing, nothing except think of poor Ducky in remembrance and weep, weep for the memories of Ducky! Sorrow, oh sorrow, he had never known such sorrow before, sorrow, sorrow, despondency, and despair, misery and desolation, oh, to be back in the happy days when he still had Ducky—and these days could be happy again, happy for Ducky, if not for you, a monster, a cold-blooded, empty-hearted villain with nothing but ice running through your head, not feeling… if only you could pity, feel for a poor, sad, miserable, despairing, despondent, sorrowful, desolate man and a poor, poor lost duck!

He continues to cry at your feet, weeping and wailing incoherently and rambling in run-on sentences. 

You stare down at him coldly, unmoved. He seems to sense that this isn’t working and straightens up, all trace of tears erased as if he were never that poor, sniveling man, prone to repetition. “Well then,” he says, “how about I double the price? Would that tempt you? This is worth a lot to me, you know…”

You consider his offer, slightly unsettled by the sudden change in the man.

If you agree, turn to section 17.

If you punch him, turn to section 51.
 
