---
title: "7"
---

You decide to take the armor. It might come in handy, especially as you don’t know what lies ahead of you on the steep mountain path. Laboriously, as the armor is rather slippery and hard to get a grip on, you pick it up and put it on. It takes you a while to figure out how to detach the helmet from the body of the suit, but you manage (it has to be twisted off, like a bottle cap). You decide not to put on the metal gloves, reasoning that any unlikely hand injuries you might sustain are less important than your current dexterity. 

You continue on the path, your pace hindered by the armor (though not as much as you’d think—it is surprisingly light). As you stare around at your early-morning surroundings, you catch a glimpse of the sun as it’s rising into the sky, preceded by fiery hues of red and yellow. You stand on a scenic cliff for a while and watch as the large fire orb ascends. In fact, you’re so focused on the sunrise that you don’t even notice the large Bird flying silently behind you until it grabs onto your shoulders with its huge, scaly talons. It’s huge, easily as large as an elephant, maybe bigger (you don’t have any elephants on hand to compare it with). It lifts you into the air but is barely holding onto the metal armor you’re wearing. Even as you rise higher into the sky, the Bird struggles not to drop you as its claws scrabble at your armor. Screaming, you hold onto the Bird’s leg so it doesn’t drop you. You don’t know where it’s trying to take you, but a drop from this height would almost certainly be fatal, as the armor you’re wearing would only make you crash into the ground harder. 

From your slightly-lower-than-a-Bird’s-eye-because-you-are-actually-barely-holding-on-to-its-leg view you can see that the Bird is currently heading straight up, wings beating noiselessly as you rise higher in the sky. You presume that it is going up to avoid the mountain (you wonder why it doesn’t go around, but perhaps this Bird isn’t very smart). An idea forms in your head.

When the Bird has reached the zenith of its flight and is directly over the top of the mountain you were climbing, you let go of its leg and frantically writhe around, trying to get free of its grip. It works! The Bird’s talons can’t hold onto you, and you fall out of the Bird’s grasp to the rocky ground of the top of the mountain. It’s only a ten-foot drop, so you land relatively unharmed. 

You allow yourself a moment of congratulations that you not only survived the clutching talons of a gigantic Bird but found a (mostly) safe shortcut to your destination as well! 

You look around the top of the mountain. It’s not a point, as you expected, but rather a circular plane, as if a giant took one of those double-ended saws, found a buddy to help, and lopped the top off long ago. 

There’s some scattered bushes and lichen around the top of the mountain, but otherwise not much vegetation. There’s also an approximately cylindrical boulder standing in the middle of the mountaintop. You go and investigate.

Sitting atop the cylindrical boulder is a skull. It’s bleached white by the sun and wind and seems to have been there for a while. Slightly shocked, you step backwards a bit, still staring at the skull. You wonder where the rest of its bones are. Suddenly, the skull’s eyes start to glow blue—dimly at first but increasing in intensity. You take another step backwards, then look behind you to make sure there’s still plenty of space between you and the edge of the mountaintop. Falling off a mountaintop would not be a pleasant way to die.

The skull starts to move its jaw up and down rapidly, causing it to jump about the cylindrical boulder, and make a disturbing rattling noise. A strange sound, like radio static, begins to emanate from the skull and its eyes grow brighter. The skull rattles and crackles around the table for at least a full minute while you look on in stunned silence. Then, all the noise and movement ceases and the skull is still, eyes glowing brighter than ever before. It begins to speak.

“Hello, traveler,” says the skull in a deep, booming voice. It sounds old, and weathered, like it has traveled many distances and seen many unpleasant things. “Welcome.”

“…?” you say. You are confused.

“Welcome…to the End of the World!” says the skull in a voice like thunder. The rocks beneath your feet rumble slightly. 

“The End of the World?” you ask quietly, and as politely and normally as you can while talking to a skull on top of a mountain after being dropped there by a giant Bird. “Pardon me, but the World doesn’t seem to be ending…”

The skull sighs, and its voice is now a lot less deep and booming. “It’s dramatic. It’s not meant to be literal. You people have no appreciation.” You’re not sure who ‘you people’ is supposed to refer to, and you’re too intimidated to ask. “Anyways,” the skull continues, “what it means is it’s the end of your world. You’re stuck here. You die. The end. RIP.” 

You look around you. There’s no path that heads down from the mountaintop, so you can’t get down, and the sides of the mountain are too sheer to climb down. The skull is right. You’re stuck. 

“You could die here, at the top of this mountain,” says the skull.

“—doesn’t sound like a great option,” you interrupt.

“…or you could jump down into the forest. There’s a dense forest down there, as well as a thick bed of moss at the bottom. You might even survive the fall, which is more than I can say for staying up here, where you will surely die.”

You don’t really trust the skull, but you also don’t see any other options.

“By the way,” continues the skull, “if you do decide to jump off, take me with you! It’s staggeringly boring up here, and I could use some excitement.”

If you jump off alone, leaving the skull here, turn to section 8.

If you jump, but take the skull, turn to section 20.

If you stay here and die, turn to section 27.
