---
title: "8"
---

You decide to jump off the cliff but leave the skull behind. You don’t want it around.

Standing at the edge of the mountaintop, you watch as a small bit of rock frees itself from the mountain at large and tumbles off into the forest. It seems like a long way down, but the trees are very tall. Perhaps they’ll catch you, and slow you down enough for survival?

“Try to bump against the mountain,” says the skull, “as you’re falling.” 

“Why,” you ask, trying to keep calm, “would I try to hit a mountain?”

“It will slow down your fall and break it into segments, which increases your chances of dying.” 

“Oh,” you say. You wonder why the skull is helping you. It has nothing to gain from this, and you can only hope that it is driven by altruism and not by some nefarious plot. “…thanks?”

“My pleasure,” says the skull. Indeed, it looks very pleased with itself. 

You stand there some more. “Now, you’re sure that I won’t die?”                                                         
“Not at all!” the skull sounds oddly chipper.

“That’s…not very reassuring.”

The skull flashes a skeletal grin as you ready yourself and dive feet first off the mountain. Following the skull’s suggestion, you try your best to steer yourself in the air towards a ledge covered in vegetation. You land unceremoniously on the edge of it, knocking the wind out of your lungs. You teeter on the side for a moment and continue your fall. Luckily for you, there are frequent ledges similar to this, and by tilting yourself you can pretty easily control your trajectory towards them, breaking up your long descent into many small, very survivable falls. 

You scream all the way down (though your shrieks are occasionally punctuated by oofs as you land hard on a ledge) until you finally land in the branches of a tree at the bottom of the mountain. 

Groaning, you disentangle yourself from the leaves and assess the damage the fall has caused. You’re bruised all over, but, miraculously, you survived! You don’t even seem to have broken any bones, though your left ankle throbs with pain whenever you put pressure on it. It’s probably just a sprain, you think to yourself as you hobble through the forest in search of a place to rest. 

After a few minutes of painful searching, you find a small cave that looks like it’ll do the job. It’s dark and smells rather odd, but you could certainly rest there for the night. You walk in and a cloud of bats, startled, flies out at you. You fall on the ground and try not to touch them. When the bats have passed, you venture further into the cave and lie down to rest.



When you wake up, there’s a large bear looming  over you. You stare at it. It stares at you. The staring is mutual. The bear begins to make loud growling noises and you slowly get up from the ground. “Nice bear,” you say. “Niiiiiiiiiiiiiice bear.” You back away slowly. It must have been the bear’s cave that you slept in last night, and clearly you were not welcome! 

As you back away, the bear lunges at you. You try to run, but your injured ankle and bare feet causes you to trip and fall to the ground. The bear lands on top of you and slices your neck open with its sharp claws, giving you, at least, a quick death.

x
 
