---
title: "9"
---

You decide to go explore the meadow. Its multitudinous clusters of tall grasses bow and sway as you push past them, further into the idyllic meadow. You lean down to smell one of the brilliantly colored turquoise flowers, and accidentally inhale an extremely large amount of pollen. You are allergic to pollen.

The pollen you have inhaled causes your nose to fill with mucus, and you try to breathe through your mouth. Alas, your throat soon fills as well with the foul slime, and you can’t breathe! You clear your throat repeatedly and attempt to expel the excess mucus from your nostrils, but it doesn’t do much help. You are still unable to take a breath. 

You collapse to the ground and feel the grainy soil beneath your face, trying once again to clear your breathing tunnels of fluid by exhaling forcefully. You manage to inhale, just a little, but enough to delay your death. You try to stand, and then you sneeze. And sneeze again. You sneeze enough times that it partially clears your airways, so you can take small, wheezing breaths. Exhausted with effort, you collapse to the ground once again.

A bee buzzes past you, landing on your nose. “Hello,” you wheeze out. The bee almost seems to aim at you an expression of distinct contempt, and promptly stings you on the bridge of your nose. 

Soon, more bees surround you, landing all over your body in a buzzing, yellow-and-black mass. Thousands of bees swarm over your thrashing, pain-wracked body, jabbing you with fierce, venomous stingers. You’ve accumulated so many stings that you can barely feel the pain anymore. Your vision starts to tunnel, and you stare up at the blue, cloudless sky. This isn’t such a bad place to die, you think.

x
