# Section 13 {#sec-13}

You decide that your puppet deserves a chance to head out into the world, away from the woods and your hermitage. You help it pack its things in a wooden suitcase that you carve for it and walk it down to the base of the mountain, a trek that takes days. It talks to you on the way about its soup aspirations. “I want to make the greatest soups in the world,” it tells you. “I wish to be famous for my soups. I shall attend soup school, to become better at soup.” You nod. 


In another couple of hours, you reach the bottom, where there’s a paved road- something you haven’t seen in decades. You hail a taxi and are amazed to see it speedily arrive. You’ve almost forgotten the sight of a car. The puppet climbs into the backseat, and you load its suitcase into the trunk. You linger awkwardly by the taxi, hands in your pockets. “Bye then, I guess,” you mutter lamely. Shouldn’t there be something more ceremonial about this? However, as gruff behavior is standard for hermits, you shouldn’t worry too much about it. The puppet grins nervously. “You’ll write?” you ask. “Yeah,” it replies. It gives you a small smile and a wave as it rolls up the window. You stand there forlornly as the taxi rolls away and watch it until it has rounded the corner, and you can no longer see it. You wonder if you will ever see the puppet again.


A month later, the first letter from your puppet arrives. It tells you that it’s having an excellent time at culinary school, and that, surprisingly, there are several other animated wooden puppets who wish to learn the art of soup-making. The rest of the letter is just a list of soups. 

The letters arrive like clockwork on the first day of each month, but the puppet never visits. Its letters sometimes have little splotches of soup on them—chicken noodle, leek and potato, and broccoli cheddar to name a few, and sometimes when you miss the puppet, you hold the letters to your nose and remember the days when the scent of soup permeated the little cabin. You never see the puppet again. It makes you incredibly sad.

x
