# 15 {#sec-15}

You decide to wear your dress shoes. You don’t wear them often, (hardly ever, really) so they’re stiff as you jam them onto your feet. Your hands fumble with the buckles, but you can’t seem to get them fastened. With rushed motions you attempt in vain to get the leather strap through the shining metal buckle frame. After a while you abandon the struggle and start running to the event venue anyways, shoes half, fastened and buckles flapping about. You can’t be late for your extremely important event! 
You run awkwardly down the street, careful not to let your shoes slip off your feet. You are not fast.

Suddenly, you are facedown on the pavement of the road, staring into the sewer. You rise, groaning, to your knees, inwardly cursing your awful dress shoes and your decision to wear them. But wait—what’s that in the sewer? You see a strange, intriguing green glow. It flickers and dims, then grows brighter again. It’s probably normal.
You’re curious, but you really have to get to your important event. What should you do?

If you examine the sewer, turn to @sec-21.

If you continue to the event, turn to @sec-62.
 
