---
title: "16"
---

You stand there dumbly, staring at the spaceship. Your feet are completely rooted to the spot as you sense something approaching. You hear the hum of a car’s wheels and see the flash of headlights, but you are rooted to the spot. 

The car speedily approaches you and you attempt movement, but, panicking, it’s like your feet are stuck to the ground, or wearing heavy, concrete shoes. You’re frozen.

The car gets even closer. Because it is a long, flat road you stand upon, you are granted the chance to see your death coming long before it arrives. As it gets ever nearer to you, you can make out the details: it’s a red sedan, rusted in places, bearing a multitude of stickers with witty science slogans on them. 

As you can see through the windshield, whoever is driving the car seems to be holding some sort of calculator and doing equations on the roof as they are driving. Presumably, this is the reason they don’t see the gigantic spaceship hanging ominously in the sky like a dead tree branch.

The car gets even closer and the scientist in the sedan suddenly looks up from the equations (it must be very important to do whilst driving and risking a ticket) and sees you standing motionless in the middle of the street, frozen in panic.

The car swerves and hastily brakes, but it’s too late…

x
 
