# Section 17 {#sec-17}

You decide to help the man in plaid.

He explains to you loudly and excitedly about his situation. It seems that he has accidentally flushed a rubber duck that he’d grown rather attached to down the drain, and he’s like some help getting it back from the land of sewage.

He describes the duck to you so that you know what to look for: according to him, the duck is small and rubber, lemon yellow with small bright orange feathers atop its small, round head. Its bill is large, and carrot colored. When squeezed, the duck emits a long, high, wheezing F#. All of these descriptions are uttered in a high, squeaky voice that’s not totally unlike a rubber duck’s itself.

You tell him that you’ll do the best that you can to find his duck, although you can’t promise anything. One object is ridiculously hard to find in a whole mountain of sewage. Secretly, you doubt his sanity.

He reacts tremendously, jumping up and down in exuberance. “Duckyduckyducky! Find ducky! Duckyduckyduckduckduckduckduckduckduckduckduckduckduck…”

His repetitions grow soft and gasping until he pauses for breath and starts again: “Duckyduckyduckyducky--” you stop him. “Okay, buddy, we get it,” you say, as if talking to a child of five. “You’re really excited about your duck!”

You think to yourself that this man seems oddly obsessed and emotionally attached to his rubber duck. You further wonder if you can trust him. 

He looks a little like your old classmate Jake. Jake never liked you because you returned all of his pencils that he’d lent to you chewed upon, and then promptly lost them when he told you to “oh, just keep them anyways.” Then you needed to be lent another pencil and the whole cycle started over again. 

Jake learned to carry a mechanical pencil at all times, and never to have any extra, in the eleventh grade, and the two of you never spoke again. You also stopped using pencils, and turned to ink pens as a more pleasant (you thought), though more permanent alternative.

What if this odd, duck-obsessed man isn’t as strange as he seems, but is really your old acquaintance Jake, driven mad by vengeance and with some evil plot in store for you? Has he come back to exact revenge? Can you trust the man in plaid, or should you back out?

If you keep your promise, turn to @sec-30.

If you back out, turn to @sec-38.
 
