---
title: "18"
---

You decide to join the slime’s band! It sounds like a fun experience, and you don’t suppose you’ll get another chance to join a band with a slime again anytime soon, so why not?

You lean down to the grate again. “Sure, I’ll join your band!” you say to the slime.

The slime is ecstatic! It jumps up and down, and its amorphous exterior sends slimy spines spiking all over the place and then returning to snap back into the slime’s main body. Then, the sewer grate stretches, growing into a wide, grated doorway with a yawning black chasm behind it. The slime glares at it for a minute, and a matching, worn metal doorknob bursts out from the grating with a loud popping noise. The slime jumps up and attaches itself to the doorknob, then twists itself to the side, opening the door, and jumps back down to the pavement. 

It then enters the portal without hesitation, speedily walking (not exactly walking, as the being does not possess legs) into the nothingness (or at least, nothing is visible) behind the open door. You can see its glowing green body steadily receding.

 After about ten seconds, it looks back at you expectantly. You tentatively put a foot forward into the blackness and hit smooth ground. You can tell that it’s not dirt, as your foot slides around slightly with each step. It feels almost like glass, but not quite. 

You keep walking towards the slime’s glow, taking your mind off of the oddly textured ground. After about five minutes, which absolutely nobody was timing on a watch, you are able to see a door at the end of the tunnel. It’s made of an indeterminate black metal with an ornate, futuristic doorknob, solid and formidable looking and eerily reflecting the slime’s bioluminescence. The slime moves towards it, speeding up (with excitement, you wonder?) and performing the same procedure you saw when it opened the door to… wherever you are now. 

The door swings open to what appears to be a recording studio if everything, all around the room, collectively decided to not make sense anymore, but only slightly, as if trying not to be noticed in their nonsensibility. (The more you consider this concept the more it applies to your current situation.) You enter, flabbergasted. The slime exits through another door in one of the walls.

The room is the same reflective metal as the passage outside, only on all four walls, plus the ceiling and floor, which would make six walls if you counted the ceiling and floor as walls, but only four walls plus a floor and ceiling if you did not.

On the walls there are multiple objects, barely reminiscent of a guitar, all electric blue and strangely matte. You surmise that these are the aforementioned ‘strummers.’ They have abnormally long necks and spherical bodies with a cut across the top, forming a hole across which strings are stretched, attached to the neck. Some of the spheres are slightly different shapes, each having its own unique globularity.

 There’s another object that you think might be similar to a bass, or at least have much the same sound, but it has two necks instead of one. Other than that, it looks remarkably like the ones on the Earth you know (but perhaps you aren’t on Earth at all, but on a distant planet. However, you have no way of knowing where you are. For all you know you could be in an underground bunker deep beneath the surface of the world you know, where life has adapted to the depth [you aren’t]). There are also drums. Drums tend to have the same basic look across all species, as the trend of beings hitting things to make noise has evolved many times. 

There are four dishlike objects set around the room. Two of them are accompanied respectively by a “guitar” and a “bass.” (These are not the proper names for these instruments, however for the sake of clarity we shall refer to them by their familiar nomers.) One of them is set near the drums, which are surrounded by a shimmering shield. Yet another is on a raised stand, alone. 

Beyond the recording room is a tiny booth, containing a stool and many switches, sliders, buttons, and various other methods of adjusting how the band-sound sounds.

As you stand there examining in minute detail the room, instruments, and booth beyond, the slime reenters the room, bringing four others of its kind with it. Each of them emitting a different glowing color: one is luminous violet, one a bright, cheerful tangerine, one is a deep vermillion, and still another is a soft periwinkle. The one you originally met is the same radioactive green as ever.

Periwinkle disappears into the sound booth, but you glimpse it placing two metal discs on top of its slimy head. Headphones, perhaps.

Vermillion takes its place in front of the standing dish-object-thing on a stand, and Tangerine glides to the “bass.” Green heads for the drums, and they all pause and look at you expectantly. You gingerly walk over to the “guitar,” and lift it over your head, letting the oddly woven strap attached to it drape around your head and under your shoulder.

Three months later, Debugged Pelican’s first 8-track tape is the number one record in the Galaxy! You spend the rest of your life recording music with the slimes and become a multibillionaire!  

x
