# 19 {#sec-19}

You decide to take the more rectangular helmet. It’s a pleasing shape and you think it looks like the perfect helmet for interplanetary exploration! 

You pick up the helmet and jam it onto your head, and it forms a seal around your neck with a wheezing sound. A panel on the side of the spacecraft has separated itself from its wall-panel kin, and they hiss its sad departure as it waves farewell. The panel falls into a ramp onto whatever planet you are currently on.

Through the hole that is now in the spacecraft, you can see a grey, sweeping landscape, which is remarkably similar to Kansas, except flatter and greyer, and plantsless. It’s beautiful if you like that sort of thing. It stretches as far as the eye can see, and you wonder if there’s any life here. Could this be the planet of the spheres? It would make sense- the planet almost seems like a gigantic version of the spheres themselves. 

The spheres bob out the paneled door, happily yelping to themselves. They then all turn back to watch you, and you wonder why they have brought you here. 

You stand in the spacecraft for a long minute. Still, they watch you. Finally, you step out of the spacecraft and slowly walk down the ramp. You aren’t wearing a spacesuit of any kind, so the air seems intensely chilly (not bad enough to freeze or kill you, more like a brisk January morning) as you step onto the alien soil. It’s not really soil, though- more of a fine grey dust that coats the planet as far as the eye can see. 

You are able to breathe normally, probably because of the helmet. The spheres are bobbing up and down, clearly happy that you are evidently able to survive their planet. 

You hear a faint hissing sound. You ignore it, (it’s probably fine! What could go wrong?) and follow the spheres, as they are floating towards an unknown destination north of the spaceship. The hissing sound gets louder, but you ignore it. The air begins to smell faintly of pickles. 

You slowly follow the spheres across the dusty ground of the alien planet. The pickle scent grows stronger with every step, as does the hissing sound, but you ignore it. You continue to follow the spheres, who don’t seem to be heading to any particular destination, but are traveling ever away from the spacecraft you arrived in. The pickle smell intensifies, and your vision grows blurry, but you ignore it. 

As you continue to follow the spheres, the hissing sound gets even louder, and you realize that you can no longer ignore it. You think that there’s a hole in the helmet, which could be causing the hissing sound. You take it off, twisting it off your head to inspect it for damage. You breathe in the alien air with some difficulty. It smells oddly of pickles, and though you are breathing it in at a normal, even increased rate, you can’t seem to get enough oxygen from it.

You realize that your helmet has been leaking this whole time, causing the hissing sound, and also admitting the pickle-scented, possibly lethal alien air… that you are now taking large lungfuls of.

Quickly you jam the helmet onto your head and run over to the spheres, as you’ve fallen behind. The hissing sound gets louder- your guess that the helmet has a leak must have been correct, and now it is widening. You wildly motion to them and point to the helmet, trying your best to get them to understand that there’s something wrong with it. You begin to feel lightheaded. You don’t think that your helmet now has enough oxygen now to sustain you. Your only hope now is to get back to the spacecraft you arrived in, but it’s now a speck in the distance and you don’t think you can make it. Still, you have to try. 

You abandon your attempt to get the spheres’ attention and sprint over the grey, dull ground towards the ship. 

As you run, you glance back towards the spheres. They seem to be confused as they stand there in a little ring. Your head is now filled with a dull pain, but you have to keep going. You know you can breathe the air in the spaceship, and you have to reach it at all costs. 

The spaceship seems to get bigger, but you’re not sure if this is because you’re getting closer, or because you’re hallucinating due to oxygen deprivation. 

Suddenly, the ground tilts and bends, rushing up to meet you as you crash to the floor, sending swirling clouds of grey dust spiraling around your body. It’s too late.

x
 
