# 20 {#sec-20}

You decide to jump off the mountaintop, and bring the skull with you. You reason that if it knew that jumping into the forest would give you a better chance of survival, then it might be able to guide you through the woods.

Holding the skull in your hand, you hesitate as you stand on the edge of the mountaintop. “Are you sure about this?” you ask the skull. 

“70%!” it chirps. “Try to bump against the mountain,” it continues, “as you’re falling.” 

“Why,” you ask, trying to keep calm, “would I try to hit a mountain?”

“It will slow down your fall and break it into segments, which decreases your chances of dying.” 

“Oh,” you say. You wonder why the skull is helping you. It has nothing to gain from this, and you can only hope that it is driven by altruism and not by some nefarious plot. “…thanks?”

“My pleasure,” says the skull. Indeed, it looks very pleased with itself.

You peer over the edge of the mountaintop and see a piece of rock loose itself from the shackles of the mountain at large, skittering over the sides of the mountain in a spritelike fashion. 

You ready yourself and look to the skull in your hands, whose jaw is set in determination. “Here goes…” you say, and jump off.

 Instead of the dramatic leap you’d envisioned, your jump turns to a sort of tumble as you half-fall, half-slide down the side of the mountain. You land on a ledge, teeter on the edge for a moment, and then resume your plummet earthwards, screaming all the way down, though your shrieks are occasionally punctuated by an oof as you hit another ledge. Luckily, all this splits your long, terrible fall, into a series of less long, less terrible falls.

After what seems like an eternity, you land in the branches of a fortunately bushy tree. Groaning, you slowly drop all the way to the ground, still clutching the skull to your chest. 

You assess the damage the fall has done. You’re bruised all over, but no bones seem to be broken. However, your left ankle hurts whenever you put your weight on it, so you try to avoid doing so. It’s probably just a sprain at worst, you think to yourself as, carrying the skull, you hobble through the forest for a place to rest. Falling down a mountain and then miraculously surviving takes a lot out of you.

You see a small dark cave that looks suitable. As you’re walking into it, the skull starts to yell at you. “WHAT are you THINKING‽‽‽ There’s a BEAR in that CAVE and you were just going to WALK RIGHT INTO IT and get me—sorry, us—KILLED!” 

You turn in reverse and apologize to the skull. “I’m deeply sorry for endangering your life. Consider me chastised, and do accept my deepest apologies,” you whisper to the skull as you backwards-walk out of the cave, trying not to make any noise so as not to wake up the bear.

“So,” you say, “if there’s a bear in that cave, is there any suitable place you’d like to stay for the night?”

The skull thinks for a minute. “There should be a little clearing, west of here, that shall be…suitable.”

“All right then,” you say, and head to what you approximate is west. The skull sighs. “Must I do everything? Set me down!” 

You set it down.

The skull then procedes to hop around in the ground, then flops over so that it is pointing in a certain direction. “There. You see? That’s West. West. Say it with me—West. Got it? Go that way.” It points to another direction. “Not that way—” it points to another direction. “—not that way—” Another direction. “—and NOT that way. West. Which way?” 

You wait for a moment and then realize that the question was not, in fact, rhetorical. “West,” you say obediently. You don’t enjoy being patronnized like this, but clearly the skull is exaspterated, so you decide you’ll put up with it for a while. You walk straight west for about an hour, only pausing when the skull yells at you that you’re not going west anymore, with such sudden intensity that on multiple occasions you jump into a tree. But, finallly, you reach the clearing. 

You lie down on the grass and stare up at the stars. “Isn’t it great to be out in the wilderness?” you say. 

“Yes,” says the skull. “Except for the bugs, and the dark, and the stars, and—did I mention the bugs—and the fact that there’s no other people around for miles—oh, and the part where we’re in the wilderness. But otherwise…A plus.” 

“Well,” you say, “as we’re both here, we might as well converse in a civilized manner. Have you much experience?” 

The skull grunts.

“Generally, people introduce themeslves first.” You do so.

The skull sighs and grudgingly says, “You may call me Horatio.”

“Is that your name?”

“Yes. Why wouldn’t it be?”

“I don’t know, usually when people tell you their names, they say that it’s their name. I thought since you said that I may call you that, that it wasn’t your actual name but how you preferred to be referred to. My apologies.”

There’s silence for a while until the skull—Horatio—says, “There’s been silence for a while. Let us now converse about treasure.” He then quiets again and you realize he’s waiting for a response. “Oh!” you say. “What treasure?”

“’Tis a tale of woe and sorrow,” says Horatio. “Well, not really, but I do find it pleasantly dramatic to start tales that way. 

“Anyways, long ago here there was a King who amassed much treasure, but feared he would be assassinated. He didn’t want anybody to know about the treasure he owned, for he thought that they might attempt to steal it from him. He had no heirs to gift the treasure to, so he hid the best of them and left the rest (gold, mostly) to his pet parakeet.”

Silence.

“What happened to the King?” you ask. “Where’s the treasure? That’s a terrible story!”

“The King? He got assassinated, just as he predicted. But the tresure is still here.

The King decided that one of his best large piles of gold, as well as a prized book, should be hidden. Actually, it has long been my goal to find one of these treasures. Would you assist me? You may choose which.”

If you decide to go after the book, turn to section 52.

If you hunt for the gold, turn to section 55.

 
