# 21 {#sec-21}

Your curiosity wins over your value of punctuality. You decide to look down into the sewer to investigate the strange green glow emanating from it.

You lower yourself back down to the pavement of the road, loose gravel scraping your cheek as your head thumps against the hard ground. Your eyes are level with the entrance to the sewer and you peer inside. You see the same odd green glow as before.

You look closer, sure you are attracting odd stares from the residents of the apartment building above you. You also dearly hope that you won’t get run over by a car, lying prone on the road like this. 

You stare at the glow for an extended period of time, trying to figure out what could possibly be causing it. Ghosts? Probably not. Ghosts clearly don’t glow green. It could be a lamp or something that someone threw down the sewer and left on, but then why would it be green? You gaze deeply into the sewer grate, trying your best to puzzle out a solution to this quandary. And to your surprise, two eyes are staring back at you!

The eyes are large and round and slightly glowing, like miniature moons. You try not to stare because you don’t know this creature, or how it might react. What is it? You don’t have the slightest idea. It could be friendly, or it could have murderous intentions.

If you just goggle at it, turn to section 63.

If you try to talk to it, turn to section 42.
