# 23 {#sec-23}

You decide to go down the path that leads to the left. While the other one leads back down the mountain, the path you’ve selected leads pretty much where you were going already as it leads up the mountain, twisting and spiraling upwards. 

You start down the rocky path. It’s an uphill climb, but not too strenuous. You start to enjoy the hike as you trek up past boulders and more boulders, beneath the grey, overcast sky and looking down upon a deep green sea of coniferous trees. 

After a few hours of hiking, the sky starts to darken as the sun sets. You look up and see that you still aren’t close to the top of the mountain and decide to make “camp” for the night (not much of a camp, however, as you have brought no supplies for such a thing) and try to find a soft bit of rock before it gets so dark that you can’t see. You spot a ledge above you and, lying beneath it, roll up your jacket into a pillow and lie down for the night. 

When you wake up in the morning, the sun hasn’t fully risen yet. You sit up and crack your neck, muscles aching and stiff from your night of sleeping on the hard stone ground. Standing, you ready yourself for another day of hiking to your goal of reaching the top of the mountain. 

Once you’re ready, you scrape some lichen off the side of the mountain as a breakfast. It’s not very filling, but there’s plenty of it, and you continue to collect and eat it as you walk up the trail. Your clothes are damp from last night’s dew, but a stiff breeze soon dries them.

As you’re walking up the trail, you come upon a curiously shiny set of silvery armor, collapsed on the ground as if someone were walking there, wearing it, and disintegrated on the spot, leaving the armor behind. You eye it suspiciously. It might be useful, but it also might just weigh you down.

If you pick up the armor, turn to section 7.

If you leave it there, turn to section 49.
 
