# Section 24 {#sec-24}

You choose a path of destruction, bent on erasing all humans’ sense of smell! 

You decide that this candle should smell amazing so that the foolish people buying them in your various retail connections give them as gifts to their friends, not ever suspecting that that nice candle that they sniffed at the store, or were given by a friend, or that was burning in that fancy restaurant the other night, could be the reason they burnt their chicken because they couldn’t smell the smoke! If you are going to discontinue all olfactory organs, you might as well make the last scent that people smell a good one. 

Once you’ve decided on a scent, you masterfully create a candle to do what you need it to.

Cackling quietly to yourself, you carefully carry the first candle of the batch into your dining room and set it on the table. Unfortunately, you trip on the way into the kitchen on the bothersome little ledge that connects the tile of the cooking area to the Compact-Disc patterned original clay tiles of the dining area. You gasp at the suddenness of the fall, your face dangerously close to the wick of the freshly made candle. But the candle wasn’t burning, so maybe it’s fine? You certainly hope so.

After a few minutes, you can no longer inhale through your nose. Was this supposed to happen? You check your notes. No. No it was not. So what went wrong?

Thinking back to the process of making the evil candle, you remember that you stirred the candle cauldron clockwise, not counterclockwise! Regretting your foolishness, you stalk back to your bedroom to sit on your bed and sulk. Passing a mirror, you glance over to it to find that your nose has vanished, leaving a gaping, gory crater where it once sat. 

Panicking, you search the whole house for your missing nose. It must be somewhere! You search under the couch. You tear up the carpets. You dig through the filth under your bed. No dice.

You have a terrible realization—what if your nose fell into the candles while you were making them‽

Grabbing all the candles you made today—you’re sure your nose was here yesterday—and a hammer, you head out to the sidewalk and start smashing the candles to pieces. Unfortunately, your nose is not inside any of the candles, and now all of your neighbors will look at you strangely as you walk by, remembering the strange, noseless person who stood on the sidewalk and destroyed candles for an hour.

Sighing, you head inside, resigned to life without a nose. You pass by the kitchen table, and there it is! Just…sitting there! You quickly pack your nose into a baggie and put it in the freezer so it doesn’t go bad.

You should probably see a doctor about this, of whom you know two—Doctor Kartoffel, whom you’ve known for years, and Dr Smith, whom a friend recommended to you.

If you consult Dr. Smith, turn to @sec-60.

If you consult Dr. Kartoffel, turn to @sec-41.
 
