# Section 25 {#sec-25}

You decide that the best thing to do with your mysteriously animate puppet is to force it to work as your servant. You tell it to do various household chores, taking advantage of its extraordinary obedience.

One day, you send it with an axe to go chop wood in the dark woods around your tiny hermit cabin. You wish to renovate your house! If the puppet could gather you unlimited wood from the forest, you could build something better than your little shack. You could build a hermit hut. You could build a hermit house. You could build a hermit apartment complex! —no wait, scratch that. You can’t be a hermit if there’s other people hermitting with you, as it completely defeats the purpose of hermitting in the first place. You might as well just go live in New York City. You could build a hermit mansion! (Or rather the puppet could build you a hermit mansion. You have no intention of doing any work yourself.) Sounds great!

The puppet toils for years doing all of your jobs while you sit in a chair it built for you believing that you were its benevolent creator, drinking Ovaltine! It begins to grow incredibly sad. It had sincerely hoped, upon obtaining self-awareness, that something like this would not happen. It had thought that you would be a benevolent and kind caretaker, not a selfish person who forces puppets to do work against their will. 

It continues to chop the wood, and carve the wood, and burn the wood for your fires, always obedient, but inside it, something stirs…

Turn to @sec-10.

