# 26 {#sec-26}

You decide to try to get the spheres to clarify what they are trying to communicate to you. You think they might assume that you can understand their strange, shrieking language because you spoke it earlier (without knowing what you were saying), but that’s not the case. 

You try to convert your English words into screamier ones that the spheres might be able to understand at least a little bit, like how speakers of Earth languages can sometimes get the basic ideas of words if they sound similar enough to the same word in their own language. You think that your plan might succeed if you lengthen the vowels in your words and scream them aloud.

You shout to them, “WHAAAAAAAAAT DOOOOOOOO YOOOOOOUUU SAAAAAAAAAY‽” You also try to indicate your confusion by tilting your head, putting your palms up in an ‘I don’t know’ gesture, and putting on your most flummoxed expression. 

Surprisingly, the spheres seem to at least somewhat receive the message that you can’t understand them. Or at least that’s what you think. You continue to make your confusion motions as they, once again, congregate in a corner to have a private conversation. You wonder why they continue to do this, as you have just (effectively, you hope) demonstrated that you do not understand them. The world may never know.

As they speak, you notice a chair-cushion-seat-thing (Cushion-chair-seat-thing? Seat-chair-cushion-thing? Thing-chair-seat-cushion?) on the floor, with many buckles attached to it. It looks vaguely comfortable, and is, of course, grey. You could have sworn it wasn’t there before, but you were so disoriented upon arriving in the sphere’s spacecraft that you may not have noticed it. 

Finally, the spheres de-congregate and one of them tilts itself over to the something on the floor, indicating that it wants you to sit there. What should you do?

If you sit down, turn to @sec-56.

If you don’t sit down, turn to @sec-02
