# 27 {#sec-27

You decide to stay on the top of the mountain. You think it’s a terrible idea to trust the skull’s statement that you might survive the fall, so you’ll just stay up here. 

The skull keeps up a constant stream of conversation, which is rather irritating. To pass the time, you dig little holes into the soft, almost clayish rock around the circular boulder, hoping that, with the large swollen clouds hanging in the sky, it will rain soon, and water will gather there, delaying your slow, agonizing death.

The skull watches you as you dig and comments about geological oddities, maps, soup, ladders, the economy, whether or not water is wet or if it just makes things wet, rain, will it rain or will the sun burn away those clouds, they look rather dark to me, I do wish there weren’t so many clouds all the time as it really messes up the natural light up here, it may not look like it but I do enjoy a little sunlight now and then, and really we’re lucky to get any sun up here as it is, and what’s that up there, oh never mind it seems to be just the Terror Bird circling again, really she means no harm, what do you mean she tried to kill you, she was just giving you a lift, no bad intentions there, and even if she was trying to feed you to her chicks, which is likely, then you would have had a quick death at least, she’s merciful that way, but don’t worry, she won’t try to snatch you again, she knows better now that your shell is too hard to eat, and by the way, why have you still got that armor on, isn’t it a bit warm for it and anyways what’s the practical usage, I mean I had a suit of armor once and all it did was sit there and collect dust, dust, dust, dust and my goodness you wouldn’t believe what happened to me when I finally put on the suit of armor, you know…

You almost feel ready to throw the skull off the side of the mountain, but you don’t, instead just stuffing lichen into its mouth. The skull looks offended for a minute and then rattles around, opening and closing its jaw in quick succession until the lichen is dislodged. “And anyways, as I was saying…” 

Unfortunately for you, the rain comes often enough that you are able to stay alive, and you live a long, bored life atop the mountain at the End of the World.

x
