# Section 28 {sec-28}

You decide to attempt to raft over the flowing magma in a raft made of floating rocks. It is a completely sane idea! 

Picking up the pointed rod from where it’s been leaning against the wall, you use it to maneuver the largest floating rock you can see over to where you’re standing. Once it’s near enough, you tentatively step one foot onto its surface. It barely sinks, so you put more and more of your weight on it until you’re almost all the way on the rock.

You then step back off the rock and crouch to a kneeling position on the floor, reaching forward and grabbing the rock, then pulling yourself forward onto it. Miraculously, the rock is holding!

Once you’re on the rock, making sure to spread out your weight to be more stable, you gently push off the shore with your feet. The raft tips forward and a bit of magma spills onto your feet.

For a moment you can’t feel anything, but then you look down at your twisted, melting feet and notice the searing heat that’s burning them to the bone. You start to scream and instinctively grab your feet, as if trying to stanch the pain, which knocks your makeshift boat off-balance and tips you into the deadly river.

Your echoing screams ringing through the cave scare away a small, easily frightened flock of bats.

x
