# Section 32 {#sec-32}

Running at your fastest, sprinting pace (still not very fast, unfortunately, as your shoes are still half-fastened), you make it to the event just in time and your event goes swimmingly! Everyone at the event seems to tolerate your presence, which is a surprise to you. You think about what you have done correctly so that you may later reproduce it, copyright it, and write a self-help book entitled Stop Floundering, it’s Bassic! The Definitive Guide to Surviving (and succeeding at) Important Events- this actually has nothing to do with fish, but I just thought it was a fun title. I am sorry. So sorry. You know what? I give up. I just give up, okay? Leave me alone. Please. Just leave me alone. (That’s a story for another time.)

You walk back to your home, broken-in shoes treading softly on the worn-out pavement. It begins to rain.

When you arrive home, you sit down at your desk in your stiff office chair. You stare out the window for a while and fiddle with a dull pencil. You sharpen said pencil. You sharpen all your pencils, and then you think about how all of them are useless because most of your writing occurs on the computer, and you prefer pens anyways, but these pencils came with the desk (they were in the drawer when you bought it and you didn’t ask questions), so you didn’t complain, you just loan them out to people and don’t ask for them back because you really don’t know what to do with them anyways.

 You think about what your future could be and realize that your life has no meaning! You can’t think of anything you’ve done in the past few years that you would remember in ten more. You stand up abruptly, hands clasping onto your desk as if it is an anchor. You can’t go on like this! You must find some way to bring meaning to your life!

If you decide to excel at puppetry, turn to @sec-46.

If you get a job at a sewage treatment plant, turn to @sec-34.

If you devote your life to the masterful creation of exquisite candle scents, turn to @sec-36.

 
