# Section 33 {#sec-33}

Disappointed that Dr. Kartoffel can’t help you, you decide to attempt surgery yourself. You set yourself up with numerous mirrors (torn from the walls of your home) surrounding your surgical area so that you can have a better view of your nose. Or where it used to be. But now it will again rule upon its rightful throne of your face… if all goes well. You carefully pick up your nose from the freezer and set it on a small metal dish on your kitchen counter, which will serve as an operating table as it is fairly easy to clean blood off of. Not that you’d have any experience with that.

You lie down on your counter and, because of your ingenious mirror setup, have a perfect view of your nasal area from all angles. Slowly, you pick up your nose and place it where it belongs. Then, you begin to superglue it to your face. You lie still for about an hour waiting for it to set, and then begin to sew it on for extra security.

Needless to say, this is an extremely unpleasant process. You flinch every time the sharp surgical needle pierces your skin and wince at the tugging of the suturing thread. It seems to take an eternity, hundreds upon hundreds of tiny, careful stitches in perpetuity. Your hands are cramping from performing the same painful motion over and over again. You vow to yourself to never, ever attempt home surgery on yourself again, but you can’t stop not with your nose half-attached to your face. You press on.



An hour later, you roll off of your counter, groaning. Your nose still smarts, but at least it’s attached. You confidently stride to the grocery store to pick up some leeks for a celebratory soup. 

On your way there you encounter a small child who gawks at you, wide-eyed. She’s grasping tightly to her mother’s hand, and, tugging on her sleeve, lisps, “Mama, why’th that nothe backwardth?” Your eyes grow larger in shock. When you set up those mirrors, you were looking at yourself upside down… and attached your nose accordingly. Flooded with shame, you sprint back up the street, around the corner, up another street, through Mrs. Ravenscroft’s backyard (you never liked her anyways) through the door, up the stairs, down the hall, up another flight of stairs, and into your apartment. You never leave it again, caged by your enormous shame.

x
