# 36 {#sec-36}

You decide to become the foremost artisan of candle scents in the world! From the time you were a child, the crafting of candle scents has always fascinated you. You used to stand for prolonged periods of time in the aisles of the grocery store, smelling the candles there. Many times, you wandered off, and your mother found you standing again by the candles, smelling them.

Holiday selections had been your favorite, and by the time you were seven your mother had learned that when she had to take you shopping with her, she should just leave you by the candles and that you would entertain yourself, engrossed in your quest to try all the scents for at least enough time for her to grab a box of cornflakes and some Bok choy. 

You start by gathering beeswax. Buckets of beeswax. Pantloads of beeswax. Wheelbarrowfuls of beeswax. Horse-drawn carriagefuls of beeswax. So much beeswax that your small apartment nearly overflows from it all! Your downstairs neighbors are furious, but there’s nothing that they can do about it. They can complain all they like, but there is, fortunately for you, nothing about excess beeswax in the city code. You’ve checked.

Chuckling to yourself, you start making your first candle. First, you pour a cup of beeswax into a metal container and place this in a pot of boiling water to melt it. Once it is melted you stir it excessively, and pour in the scent of lavender, which you have extracted from flowers that reside (or resided, past tense is more appropriate here because the flowers now reside in the candle, or their scents, anyways) in your garden.

Once this is all sufficiently stirred, you place a wick with a small metal cap on its base into your chosen wax receptacle. It is a jar. You slowly pour the wax into the jar and wait for it to set.

Later that evening you light the candle. It smells great! You realize that there is a business to be made here and decide to call your friend who is a business expert. You dial his number on your mobile phone, and he picks up on the twelfth ring. Lazy. 

You greet him and tell him about your proposition. He tells you that a candle business is a great idea! If you can make good enough scents, success is imminent! You feel that you’ve made a delightful selection in your career. Fueled by ambition, you begin a list of candle scents to make.



Years later, you’ve created a candle empire! Your candles are in supermarkets everywhere, and you get a little sentimental thinking about all the children in those supermarkets, smelling ALL the candles, just as you once did. They now have quality candles to enjoy, not monstrosities like Grated Onion and Beige Monotony. You’re pleased with your work.

However, you’re getting a little bored. Making candles is fun, but it does get dull after several years. You want to do something different! Something revolutionary.

As an expert in candles, you want to further your skills, so you check out a book from the library on how to make magical candles with rare ingredients, such as dragons’ teeth, newts’ eyes, and the like. To your surprise, it’s not terribly difficult. 

You think up two ideas for a new and exciting candle: a candle that makes everyone within a five-foot radius of it while it’s burning immune to the common cold, or one that damages the noses of everyone within a twenty-foot radius, to the point that their sense of smell is completely gone. Which to make?

If you make people immune to colds, turn to section 50.

If you destroy people’s sense of smell, turn to @sec-24
