# Section 37 {#sec-37}

You decide to stay and fight the hunters!

*We should fight the hunters!* you tell Agreeable Gray. *I think we can beat them. Besides, every time you’ve run away they found you again! Maybe it’s time to give something new a try.*

*I agree with you!* says Agreeable Gray. *That’s a good idea.*

Agreeable Gray waddles over to a makeshift lectern made of an old stump. *Fellow platypuses!* she calls in a stirring tone. *For so long we have been pursued by the hunters, killed off one by one to be shipped off and turned into hats, and I mourn for our fallen friends and family.*

*Before now, all we have done is run away, but today? Today, we strike back! We refuse to live in constant fear, perpetually looking over our shoulders for the menace always lurking there.*

*For there are hunters right outside our door, and instead of fleeing, I say we stay and fight!*

A cheer rises from the puddle of platypuses gathered below her.

Those of you with venom, be prepared to use it. Bring extreme pain and force them to regret that they ever began to kill our kind for their idiotic hats!

Another cheer, and the crowd disperses.

It’s not long, though, before the sound of horses whinnying and of shouting. The platypuses assemble in fighting positions around the bush/entrance to the tree-enclosed lake, looking fierce—as fierce as a platypus can look. You take a position near the back of the group.

Crashing through the trees come the hunters, yelling battle cries and brandishing their bows and arrows, bickering with each other about whose bow is more accurate; whose arrows are sharper and whose are the swiftest.

They soon quiet, however, when they see the platypuses assembled around them, rage in their beady eyes. Agreeable Gray growls, and the platypuses spring upon their enemy.

The hunters are shocked to see so many of the small, furry creatures they’ve hunted for so long show a backbone and are slow to react, hardly getting a chance to reach for their quivers as the force overcomes them.

There’s enough platypuses that each hunter has to face three or four of them, and the platypus’s venom makes it a devastating enemy. 

Hunters fall to the ground, writhing and spasming in agony. You grab onto the back of a large burly man, scratching his back with your flippers. He shakes and jumps around, trying to get you off, but your hold is fast. 

While you have him distracted, a platypus you’ve seen before—what was her name? Majestic Mauve? Something like that—pummels his face, catching him off-balance and knocking him to the floor, where he promptly hits his head on a tree root and falls unconscious with a grunt. Mauve parades over his face in satisfaction.

Looking up from your battle, frantic from panic and excitement, you see that although the platypuses have overwhelmingly won the day, there are some unfortunate casualties. Agreeable Gray, for one, lies limp on the ground, her face frozen in a fierce battle cry.

As you look on, the hunters are getting back on their horses and retreating, galloping much faster than necessary through the undergrowth. 

Urbane Bronze approaches you through the fast-settling dust of the battlefield. *Although I was Agreeable Gray’s second in command, I don’t think I’m quite ready for a position of authority. You fought bravely today for our community, though you’ve just arrived. It would be my honor to offer you her position as leader of our puddle.*

Thinking it over, you see no reason to refuse.

*I’ll take the position,* you say.

You rule over the puddle for many prosperous years. 

x
