# 38 {#sec-38}

You decide to back out. You don’t really want to want through a whole plant full of sewage just looking for this guy’s stupid duck. Anyways, he looks a little… *you swivel your right index finger next to your head and let out a two-note whistle*. You take a step backwards towards your car. “Hey,” you say in an overly calm voice, “I don’t know if I still want to do this. I’m gonna get in the car now, okay?” You take another slow step backwards. 

The man seems confused. “Y-you don’t want to help me find my duck‽” 

“Maybe you can find it yourself tomorrow. I’m leaving now…”

He rolls up his garishly plaid sleeves and the fire of rage burns in his pupils, which now have images of rubber ducks spinning and growing in them. “YOU ABANDON DUCKY‽‽‽ YOU GO BACK ON YOUR WORD‽‽‽ YOU SHALL PAY!”

He lunges at you, and you attempt to throw him off, but he’s surprisingly strong. He punches you in the face and it turns into an all-out brawl. You remove his fingernails. He bruises your colon. You remove his eyebrows. He scratches your cornea. You bruise his esophagus. He uses the remaining stubs of his ruined fingernails to scratch long scratches down your arms. As you fight, he gets in a particularly hard punch to your gut. You scream, then clench your jaw and turn in increased rage.

Turn to section 64.
 
