# 39 {#sec-39}

You decide that you should probably hire a lawyer. After all, you know next to nothing about the law except for the fact that it is long and hard and doesn’t make much sense to an outsider (not a lawyer). 

You hire a man named Joseph Yorke, whom you selected by taping the ‘lawyer’ yellow pages to the wall of the living room of your home and throwing a dart at it. He seems capable enough, judging by the extreme firmness of his handshake when he greets you in the lobby of his building, and the profoundly serious tie he wears around his neck. He directs you to go up the stairs and to the left, and dissipates into thin air.

 You flap your hand wildly about in the air to alleviate the pain he has caused as you walk melancholily to his office. You think that your fingers may have been fractured. (They have not.) 

You knock three short times with your left hand (which he did not shake, fortunately your lawyer is not one of those people who shake both hands, bringing equal agony crashing down upon both) on the frosted glass door, framed in wood. For a second you wonder vaguely if it’s one of those kinds of things in which the occupant of the room can see out, but nobody can see inside, or vice versa. 

He opens the door and ushers you inside. You sit in a carefully uncomfortable chair—it is just so uncomfortable as to make you squirm, but not so uncomfortable that you feel it appropriate to ask for its replacement. 

He clears his throat. 

“I understand you’re being tried for murder,” he says in a cold, dry voice, like the Sahara Desert in winter. You confirm. “Right,” he says, and both of you stare absently at each other until you are called down to the court.

Mr. Yorke defends you brilliantly at the trial, providing a perfect defense for each of the prosecution’s cutting attacks. You are cleared of all charges and are extremely grateful. Clearing his throat, he hands you a small envelope.

Turn to section 43.
