# 40 {#sec-40}

Rafting across the magma river on a rock seems like... a bad idea. You decide to attempt to jump over it instead, using the long pole resting against the wall of the cave. 

With some difficulty, you climb up the face of the cavern to the ledge above you, scraping your feet on the crevices in the wall. You now have a high vantage point from which to jump.

 Unfortunately, you’ve forgotten your pole. You sigh and climb back down from the ledge, grab the pole, and throw it up to the ledge. It bounces off. Again, you toss the pole up to the ledge. It lies there for a moment, then rolls off. 

Frustrated, you repeat the process several times, each ending with the echoing clatter of the rod landing on the cave’s floor. Trying a new strategy, you grab the pole in one hand and try your best to climb up to the ledge with only three limbs. 

The pole, though light, is large and unwieldy, making it difficult to climb up a wall (though the rock handholds are conveniently plentiful) next to a river of magma. You make it up the wall and pull yourself up onto the ledge, still tightly gripping the vaulting pole.

The view down from the ledge is rather unpleasant—it’s a long way down to either solid rock or its molten counterpart. Nervously, you stretch the rod out over the burning river and set it down the magma. It sinks slowly and doesn’t seem to be disintegrating, which is a good sign, at least! 

Once the rod has sunk to the bottom of the river, you ready yourself, drying your nervously sweating palms on the front of your shirt and grabbing the pole. “Here goes nothing,” you mutter to nobody in particular, and jump off the ledge. 

Screaming all the way across the river, you swing through the air, keeping a death grip on the pole. The wall opposite is heading towards you at an alarming rate. You’re going too fast! You didn’t think it was possible, but your screams increase in both volume and intensity as you hurtle towards the sheer rock. 

You crash into the ledge and your momentum keeps you going into the wall, but the rod bounces off the ledge and into the river of magma, effectively foiling your plan of egress. There’s no going back now. 

Clambering down from the ledge, you walk over towards the cave-hallway. Giving one last nervous glance towards the menacing river, you walk down the long, pitch-black hallway as the red glow of the magma recedes behind you. 




You reach the end of the hallway and come upon a cavern even larger than the last, with the glowing blue reflections of water glimmering and shifting on its ceiling and walls. The chamber is shaped like a semicircle, and the hallway you emerged from is right in the center of the arc. There’s a little doorway in the upper left corner of the room, with a rocky ladder of small ledges leading up to it.

In front of you, the floor dips dramatically, creating a large water-filled pit in the room that disappears under the straight edge of the semicircle. 

In the center of the pool is a majestically large, purple octopus, or so it seems. In the dim light of the room, it luminous, pure white eyes cast dramatic shadows over the craggy rocks lining the sides of the room, and its enormous head stretches up almost to the ceiling of the cavern. Its tentacles aren’t visible, presumable stretching deep down into the depths of the pool.

“Hello?” booms the octopus, in a deep, authoritative voice. You let out a tiny, terrified squeak. You wonder why it can’t see you—you’re not in the least hidden. Then you look up at its white, glowing eyes and realize that it must be blind.

“I know I heard someone come in. Who is it? I won’t hurt you. Or eat you. I mean, that wouldn’t really be painful, but you get my meaning.” 

The word of an octopus is good enough, you suppose. You don’t think you’ll be getting a better one, and you have nowhere to go, your rod having fallen into the river of magma. You guess that your best bet to get out of here is to talk to the giant octopus thing and somehow convince it to let you past, and through the little doorway behind it—hopefully to somewhere that’s not a cave. 

“H-hi,” you stammer quietly. “I’m here, I-I came in through that hallway over there.” You gesture towards it, than realize that the act is futile if your suspicions are correct about the octopus’s sight, or rather lack thereof.

“From the sound of your voice you’re… human?” says the octopus, its voice like thunder. The statement lilts upward towards the end, as if it’s not really sure. “My. I haven’t seen one of those in years. Well. I haven’t seen anything in years, but you know what I mean. Most living beings around here are fish, spiders, or whatever it is that’s hiding down here in this deep pool. Can’t see it, but it swims around me from time to time. Drives me crazy. Anyway, what can I do for you?”

You’re rather stunned, both by the octopus’s remarkable amiability (or so it seems—you still don’t quite trust it) and its question. “What can you… do for me?” you ask, incredulous. 

It is a giant octopus, and you are a relatively small human, completely at its mercy in its home territory… and it wants to know what it can do for you? 

“Could… could I have a sandwich? Or some shoes?” you ask. You’re rather hungry, and your unshod feet are starting to ache. 

“No,” says the octopus. “Unfortunately, I can’t do that. I lack both shoes and sandwich supplies, but I do have limited (alas, quite limited) magical abilities.” It pauses.

“Go on,” you encourage.

“Sorry about that. Lost my train of thought there for a second. That infernal creature is swimming past me again. I swear, it’s trying to intentionally anger me! It’s probably just a stupid little fish, but every time I try to catch it, it just… slips right out of my grasp!” It lifts a great tentacle out of the water, forming a fist and shaking it in anger and frustration, but thoroughly splashing you with water. 

“Sorry about that. As I was saying…” it begins to mutter to itself, seemingly replaying what it said before to find its place in the conversation. “Yeah, no sandwich, no shoes, limited magic but did I explain—ah!

“Yes. I was saying, my magical abilities are limited but present. I can turn you into one (1) of three things—a washcloth, an onion, or a platypus.”

It’s an eclectic selection of items, but you should probably appease the octopus and choose one. The octopus seems eager to please and assist now, but there’s no telling how long this attitude will last.

If you ask to be turned into a washcloth, turn to @sec-67.

If you ask to be turned into an onion, turn to @sec-65.

If you ask to be turned into a platypus, turn to @sec-61.

