# 46 {#sec-46}

You decide that the best way to bring meaning to your life is to devote it to becoming an expert in puppetry! You move to a small hermit house in the mountains and build all sorts of puppets out of the wood you have chopped from the dark woods all around your Cabin of Ultimate Introversion. These woods are extremely useful to you: they keep out stray children looking for suspicious gingerbread architecture, and they supply materials for your life’s work.

One day, you decide to make a puppet that looks like a humanoid! You chop wood, then get out all of your extensive collection of carving tools. You work night and day on this masterpiece.



After weeks of endless toil, you are almost finished! You just need to attach the strings to its limbs, joints, et cetera, but you need a break. You finally rest, intending to get back to work in the morning.

You wake up in the middle of the night. Something small and wooden doesn’t quite loom over you, although you can tell it’s trying. You give it points for effort as you pretend to not be terrified of it. 

It taps you on the shoulder, evidently wondering if you’re awake. You stare at it and realize that it’s your puppet! Your puppetry masterpiece is staring right back at you! You wonder who’s controlling it (and how this person has access to your house, and why they are using a puppet to wake you up in the middle of the night…) until you remember that you never attached the strings! 

Obviously, the puppet has somehow animated itself. But is it a friend or a foe? The puppet’s wooden face stretches unreasonably into a smile. It clearly doesn’t mean you any harm, but what should you do with it?

If you decide to make it work as your servant, turn to @sec-25. 

If you decide to adopt it as a child, turn to @sec-44.

