# 48 {#sec-48}

You decide to try to be friendly to the alien spheres. After all, being nice to them might mean they’ll try to be nicer to you, right? You certainly hope so.

You gulp and try to start a conversation, but it’s difficult, as you have next to nothing in common with the spheres.

You clear your throat. “H-hey!” you stammer. “H-how you doing? I really can’t complain, but, you know, I do have a really important event this morning!” Sweat begins to roll down your neck. “S-still though, really happy to be here with you folks, it’s real great. You sound like real great people and it’s a pleasure to be here, real pleasure, but I really was wondering if you could set me down, put me back on the road? I mean, I’d be so sad, really, devastated, to leave but you know I’ve got this thing, this event, you know how it is, these things can’t be helped…” You trail off.

The spheres stare at you blankly. Even though they don’t have eyes, you can feel them looking at you, and those stares are confused and judgmental. 

Suddenly overcome by your situation, you begin to scream loudly and uncontrollably. Your screams are long and loud, and soon the spheres bob up and down in the air as if in agreement. Then, they begin to scream themselves, guttural yells from unseen mouths. 

You continue to scream at the spheres, and they scream back at you, occasionally clearly directing the screams at each other. This must be how they communicate! 

So far, they seem to be agreeing with you, but you don’t know what you’re saying to them. Do you continue to try to communicate to them through screams, or stop?

If you continue to scream at them, turn to @sec-03.

If you stop screaming, turn to @sec-58.
 
