# Section 49 {#sec-49}

You decide to just leave the armor there. It looks quite heavy and would probably just weigh you down. Additionally, you haven’t seen anything (or anyone…) that would require armor to fend off. You walk off to continue your hike to the top of the mountain. 

Hiking along the trail, spiraling ever upwards (are the spirals getting smaller? Could you be getting closer to the top? You hope so, as you are tiring of the endless circles you find yourself walking in), you spot the sunrise. It’s like a painting, the sky swathed in saturated shades of brilliant red and yellow. You look out over a scenic cliff and stare at it for a while as the sun makes its daily trip across the sky (or appears to—clearly the sun is not actually traveling around the Earth and across its sky because it is the other way around. The author pleads dramatic license in trying to accurately portray the look of the scene), creating fiery colors in its burning path. You continue to stare at it, so taken by its beauty that you don’t even notice the giant Bird swooping down over you until its large, sharp talons dig into your shoulders. 

You scream as the freakishly large Bird carries you off into the sky, wings beating steadily, barely hindered by your extra weight. As you beat at its legs and desperately try to prise its talons off your shoulders, the Bird instead grips you harder. You gasp in pain as its claws pierce your clothing and then your skin, sending rivulets of blood dripping down your shirt and onto the ground, far below you. You grip onto its scaly legs, trying to shift the weight from your shoulders so that the wounds on them are not the only things holding you up, widening the cut and increasing your pain. 

The Bird doesn’t seem to be taking you to the right or the left very much but is flying over the mountain you were climbing and past it towards one of the adjacent mountains. From your elevated viewpoint, you can see that on the side of the mountain lies a staggeringly enormous nest. You wonder if that’s where the Bird is taking you. As you fly closer, every beat of its wings shaking you and sending a fresh wave of pain through your shoulders, you see three large, huddled forms in the nest. Chicks. Oh no, you think. You see where this is going. 

The Bird drops you into its nest, landing beside you and severing your head from your body with one quick twist of its wickedly sharp beak. 

Your body is eaten by the chicks, who grow up to be full-fledged, healthy Terror Birds on a nutritious diet of travelers like you. 

x
