# 50 {#sec-50}

You decide to create a magical candle that eliminates the common cold. You despise colds. They cause you endless irritation and frustration, and you always seem to have at least one a month. You masterfully craft a candle, magically imbuing it with the power to obliterate colds. Also, it smells like lemons! 

You congratulate yourself on your dual triumph and decide to test it before distributing it to the public!

You light the candle and waft the scent through your olfactory passages. You try to inhale again but find that you can’t!

Your mind races, wondering how this occurred. Trying not to panic so you can conserve oxygen, you run through your candle making process again in your head. You poured the wax right (is it possible that the wax has filled your airways, obstructing them? No, probably not—the wax was set thoroughly. You dismiss the thought), put in the scent correctly… but did you stir it right? You think hard and remember that you stirred your pot of wax clockwise instead of counterclockwise… turning the otherwise harmless candle deadly.

You think halfheartedly that you won’t be getting any more colds anyways, so technically your candle succeeded. Deliriously you cheer, or at least you think you do, starting to feel the effects of oxygen deprivation.

You collapse on your threadbare sofa, your cheek mushed into the fabric. 

Funny, you think, this isn’t really how I expected to die… I’d hoped that the circumstances would be a bit more heroic or exciting. But slowly suffocating on the sofa is rather dull… You are disappointed.

Slowly your vision starts to tunnel, and then goes completely black…

x
