# Section 51 {#sec-51}

Who is this man to ask you to wade through sewage for him? 

Your years sloshing through sewage have made you aggressive, and you decide that your best option is to punch him, just to explain that you refuse to be harassed by this strange man who has lost his duck.

 You don’t think he knows how to fight very well. You narrow your eyes. “Well, what if I don’t wanna find your stupid duck?” you scream at him, suddenly agitated. You are unfortunately aware of how much you sound like a petulant child yelling at its friends on the playground. “THEN YOU SHALL PAY!!” he screams back at you with great force and intensity. 

This shouting match goes on for a while. He insults everything you love and care about, and you tell him that ducks are stupid, and that no one cares about them and they’re just waterproof chickens with kazoos anyways! You find yourself using the word ‘stupid’ an increasing amount.

He rebuts on the great and amazing qualities of ducks, especially rubber ones, how they cause him joy and how you are SO STUPID to have thought that they’re just a different form of chicken because really, what similarities are there? He continues on and on, indignant.

The two of you hurl awful insults at each other for hours and your voices are hoarse. You whisper terrible things into one another’s ears until you decide you’ve had enough of the insults. They aren’t getting your message across, so you decide to express yourself in a different way.

You pull back your fist and punch him squarely in the jaw. He stumbles back, surprised. His eyes begin to glow with lava-like anger.

Turn to @sec-12.

 
