# 52 {#sec-52}

You decide to go for the book in the forest. It sounds…interesting, to say the least, and you wonder if it has yet decomposed, as books left lying in the woods are wont to do. “Let’s go for the book,” you say to Horatio.

“Good choice,” he says. “The book is hidden deep in the Forest of Terror.” He draws out the last word, making it sound extremely dramatic and spooky. “That’s…good?” you say, rather intimidated by the name of the forest. “Tell me, does that name have any truth to it?” 

“Oh, the ‘Terror’ part?” 

You nod.

“Absolutely! They wouldn’t name it that if it wasn’t true. Don’t worry, though. It’s really not quite as bad as it sounds.” You hadn’t really been worrying in the first place, but as being told not to worry indicates that there is, in fact, a reason to do so, you are now rather concerned about your safety. 

“The forest isn’t far from here,” Horatio continues. “There’s a little trail that starts about ten minutes’ walk away. Also, you should probably pack some food. Once we get into the forest, it’s quite the trek to get to the book.” 

You gather some of the edible leaves, berries, and such from the area around you and take off your jacket. You lay the jacket on the ground, placing the gathered food inside of it. You zip up the jacket, tie the head and torso holes closed, and tie the arms around a long stick. 

Horatio directs you to a small path that leads downhill into a sparse forest. The path continues down until the trees begin to thicken around you, then flattens out. As you walk cautiously into the forest, you ask Horatio if this is, in fact, the Forest of Terror. 

“You could say it’s on the outskirts,” he says. “We are, technically in the Forest of Terror, but the ‘Terror’ part hasn’t really started yet. You could say that we’re in the Thicket of Mild Panic.” 

“Wonderful,” you say, without much conviction. “And when, exactly, does the terrifying section of the forest begin?” 

“It’ll be about half an hour’s walk from here. There’s a ring of less-terrible forest around it, in which we are right now.”

You walk in silence for a while. The trees, at least, are nice to gaze at. Though at first glance many of them look familiar, upon looking closer you see that they are paler, thinner versions of their counterparts. Their leaves are translucent and their bark worn and twisted, like a shriveled piece of hair left in the bottom of the shower to dry out and be rehydrated, again and again and again until it is but a shell of its former self, lying defeated on the unforgiving floor beneath it. 

As you walk, the sky begins to darken, as if night is prematurely falling. You look at Horatio with worry in your eyes. “Is this… the Forest of Terror?”

“Nod,” he says. Obviously, he is unable to nod without a neck with which to do so, so you suppose this is his approximation.

The sky continues to darken. After a few minutes, you can’t see your hand in front of your face. Luckily, Horatio’s glowing blue eyes provide some illumination, and you hold him out in front of you to see—if dimly—the path beneath your feet. 

Shortly, however, this becomes unnecessary. Suddenly, the tree beside you lights up with a brilliant lilac-colored light! The flash blinds you temporarily, and as you blink furiously you see trees all around you have lit up spectacularly in a blazing display of colors. In wonder, you touch the rough bark of a particularly tall tree in blazing chartreuse. 

Horatio looks unimpressed, but that may be due to his lack of expression. 

“Is this…it?” you ask. “Is this the whole ‘terror’ thing, or is there something worse, ahead or what…” 

“This is it! You have arrived at the Forest of Terror.”

“It’s not very…terrifying.” 

“I was asked by the PR manager of the forest to refer to it as such. If people knew what it was truly like here, it would be overrun by tourists, campers, and people in general. Apologies.”

“If we go back the way we came, will it go back to being normal daytime?”

“Probably.”

“Why are the trees glowing?”

“No idea.”

“No idea?”

“No idea. Now stop asking questions, or the path will go away.”

“Really?”

“No. Just stop talking. Please.” 

There is silence. 

Silence for tree-lit days, silence for tree-lit nights. You cannot see the stars or sky, so you can only infer the day-night cycle. The silence is absolute and overwhelming. Back home, you could always hear something—the hum of a computer, a chirping bird, people talking in hushed whispers. But now there is no sound save for the muffled impact of your shoes upon the ground. Sometimes you stop and listen, straining your ears for a sound, any sound. You are unsuccessful.

You think it’s been a few days, but you’ve rather lost track of time. Horatio breaks his days-long silence when the path turns around a corner and suddenly comes to a full stop at the foot of an extremely large, extraordinarily bright tree. “Here,” he says.

As earlier stated, this tree is extremely large. Twenty dolphins, with each one’s nose touching to the tip of the tail of the one before it, would form a ring smaller than the circumference of this tree. 

The tree appears to be hollow, with a large entrance in the side. You can’t see into it. 

“Go inside,” says Horatio. With reservations, you do so.

Once you set foot in the hollow of the tree, there’s a clicking noise and a spotlight shines down a long, dark hallway with wooden walls, illuminating dust motes in the earth-scented air. You step down the hallway. It seems longer than it should be, even considering how big the tree is. 

You arrive at the end of the hallway. There’s a pedestal with a large, wooden button on it. Horatio directs you to push the button. 

The button seems stuck. You push harder and it gives. There’s a grinding, crunching sound, like that of reluctantly turning gears. The pedestal raises up above your head and clicks open, revealing a secret compartment inside it. It looks like a little cabinet, with a shiny brass knob—the only thing you’ve seen so far that isn’t made of wood. 

You reach up and open the knob. A little book tumbles out of the compartment. It’s…not dramatic. The book falls into your waiting hands. You inspect it. 

The book looks rather ordinary. Its cover is leather and its pages old and yellowed. You open the cover and, to your great surprise, no shining light is emitted by the book, shining onto your face cinematically. You look at the first page. It’s blank, so you turn to the second page. 

The markings on it are illegible, at least at first. You stare at it, trying to make sense of what seems to be scribble upon scribbles. Suddenly, the scribbles start to move, wriggling like a large group of worms. It arranges itself into words. 

*Greetings, traveler,* it says. *Thee hath found the treasured booketh of the King! Thou art anon the rul'r of the landeth. Congratulations, and enjoyeth thy ruleth!*

“Is that… good?” you say to Horatio. 

“Quite,” he says, in a deadpan manner. “You are now the ruler of the land!”

“Who was the last ruler? Have they been notified?” you ask, rather concerned for the state of the land.

“The last ruler was the King who hid this book. The land has been living in anarchy ever since,” Horatio says in a rather dramatically world-weary voice.

“I can’t save all these people from political ruin!”

“People? What people? This land is unpopulated, except for the PR manager of the forest, but he takes care of himself. You don’t have to worry about him.

“Anyways, the King built himself a palace, sectioned off the land, and declared himself the ruler. Nobody questioned it because there was nobody there to do so. You wouldn’t actually have to rule over anything or anyone, just live in a palace.”

“Why…did the King get assassinated if he lived in a palace, alone, in an unpopulated ‘kingdom?’” you say, incredulous at your current position.

“He amassed a lot of gold in his life. People tend to steal that sort of thing.”

“And if the kingdom is empty, and only existed because he said so, why did he hide this—” you gesture with the book, waving it around “—in a cave in a weird glowing forest in the middle of nowhere?” 

“To answer that question, attend my seminar in *Motivations of Medieval Monarchs: A history.* Anyways, now that you have a palace, shall I lead you there?”

“Verily,” you say. 

x
