# 53 {#sec-53}

You think that the platypuses’ community should run away from the hunters trying to skin them. 

*I think we should run away,* you tell Agreeable Gray. *It’s worked before. Plus, we don’t know exactly how many hunters there are. There could be hundreds! It’s just too much of a risk to fight.*

Agreeable Gray nods. *I think you’re right.*

She climbs up on a tall stump to address the rest of the puddle. *Fellow platypuses! she says. Hunters have again found our hiding place, so I regret to inform you that we must again flee. For the fifteenth time, we will find another place to live. Again.*

*Lives may be lost in the process, but we will always come out on top. We can do this!*

There’s murmuring in the gathered crowd, whispered doubts and fears. Puggles come up to their parents and ask them what’s happening.

The susurrus is interrupted by the crashing and crunching of branches and dry leaves and the whinnying of horses. The hunters burst into the enclosed lake, yelling blisteringly loud and firing arrows everywhere. 

The horn stops blowing. Either Olde World Gold is dead, or has decided to stop the alarm because everyone is already aware of the presence of danger.

You watch, horrified and frozen in your position on the shore of the lake as the hunters decimate the population. Urbane Bronze falls, an arrow in his heart. Currency changes hands between the hunters—they seem to have a bet on who can bag the most platypuses with the best pelts.

You run over to Urbane Bronze. He’s still breathing, but it’s shallow. Looking up, you find yourself starting right into the murky grey eyes of a hunter, perched atop his horse with a cruelly sharp arrow pointed straight towards you.

You lunge away but feel a sharp pain blossom between your ribs, and the world goes dark. 

x
