# Section 54 {#sec-54}

You really don’t think you want to be in a band with the slime. It sounds to you like an extremely unpleasant experience, like having your nasal hairs ripped out one by one by a cackling piece of fruit.

You tell the slime that no, you would not like to join its band, you’re really not that good on the ‘strummer’ anyways and it wouldn’t want you on its band in the first place but you’re glad it asked, really, you’re honored and hey, look at the time, you have this event you’ve got to get to, so you have to leave now…

You trail off as you see the look in the slime’s bulbous eyes. They are lit up like really angry lakes.

You realize that however kind it may have been of the slime to invite you to its band, it’s clearly not feeling very benevolent now that you’ve offended it by refusing its offer.

As you stare at the slime, and the slime stares at you, your blood begins to bubble and fizz. It grows increasingly bubbly and tickles at first, but soon grows painful, intensifying into the stinging prickles when you’ve cut off circulation to a limb. The sensation worsens until you are in great distress. The slime almost grins (or perhaps it is fully grinning because you really can’t tell facial expressions on a slime. They’re far too slippery). As it stares at you, you realize that it must be the cause of your blood-bubbles! Clearly this being was more malevolent than it seemed.

No one notices as you flop around in agony on the pavement, your blood growing increasingly aerated until, finally, you burst…

x
 
