# Section 56 {#sec-56}

You decide to sit down in the V-shaped chair-cushion-seat-thing. Your justification for this is that your life has been, up to today, rather dull, and lackluster. Going on a space adventure—for that is assumably what you are about to do—is exciting to say the least. If you are late for your very important event, you of course have the absolute best alibi of alien abduction.

You sit down in the chair. As you expected, it is no more than vaguely comfortable. You suspect that its excess of cushions is for safety reasons rather than comfort. You buckle the buckles and think about how cool it is that one word can be a noun and a verb at the same time, and how confusing. 

As soon as you are bucked into the seat, the whole spacecraft suddenly accelerates upwards and forwards in a diagonal fashion. You are pressed hard into the cushioned seat. Although you can still breathe, it’s difficult. You’re glad that you are strapped in. Otherwise, you might have died! Strangely, this does not seem to affect the spheres in the slightest, as they move about in the air as effortlessly as they would in a normal scenario, or at least as normal a scenario as one can be in which you are encountering sentient spheres.

After the initial acceleration, the pressure lets up a bit and you’re able to breathe normally once again. 

After about thirty rather uneventful minutes by your estimate, (although it is completely possible that your sense of time is off. You have been known to disappear into a book or project for ‘just five more minutes’ and then be found an hour later still engrossed in your task), which you mostly spent staring out the scuffed windshield at the pinpricked blackness of space. As you watch, a planet comes into view, getting closer and closer until you’re sure that this must be the destination.

The pressure lets up completely and there’s a faint hiss as the spacecraft, you presume, lands. You unbuckle your harness and get closer to the windshield to get a better view of the landscape. The spheres have a little shrieking conversation in the corner. 

The strange planet you look out upon is grey, barren, and perfectly spherical as far as you can tell. You can see for what must be miles into the grey wastes, stretching infinitely to the horizon line. You turn back around and there’s a table on the floor that you don’t remember being there. Perhaps the spheres are capable of moving at much faster speeds than is evident, and they moved it while you weren’t looking.

On the table, the spheres have placed (although how they place things on tables without hands, you don’t and probably will never know) two helmets. They are both crafted of transparent glass, or at least some substance that possesses the transparent quality of glass while still managing to softly glow incandescently in the dim, artificial lights of the spaceship. One of the helmets is a perfectly spherical and the other is a rounded rectangular prism.

It’s clear from their expectant looks that they want you to take one of the helmets, presumably for a journey onto whatever planet you’re on. Could it be the planet of the spheres?

But which helmet to take?

If you take the rectangular helmet, turn to @sec-19.

If you take the spherical helmet, turn to @sec-57.

 
