# 57 {#sec-57}

You opt for the spherical helmet. It’s so nice and shiny and it looks like a fishbowl- clearly it is the best choice for interplanetary exploration. 

You pick up the helmet and jam it onto your head, and it forms a seal around your neck. 

After a few seconds, you hear a pneumatic hiss. A panel on the side of the spacecraft has separated itself from its wall-panel kin, and they whisper sad goodbyes to it as it waves farewell. The panel falls into a ramp, which in turn falls onto whatever planet you are currently on.

Through the hole that is now in the spacecraft, you can see a grey, sweeping landscape, which is remarkably similar to Kansas, except flatter, greyer, and without any plants. It’s beautiful, if you like that sort of thing. 

It stretches infinitely to the horizon, and you wonder if there’s any life here. Could this be the planet of the spheres? It would make sense- the planet almost seems like a gigantic version of the spheres themselves. 

The spheres bob out the paneled door, happily yelping to themselves. They then all turn back to watch you, and you wonder why they have brought you here. 

You stand in the spacecraft for a long minute. Still, they watch you. Finally, you step out of the spacecraft and slowly walk down the ramp. You aren’t wearing a spacesuit of any kind, so the air seems intensely chilly (not bad enough to freeze or kill you, more like a brisk January morning) as you step onto the alien soil. It’s not really soil, though- more of a fine grey dust that coats the planet as far as the eye can see. 

You are able to breathe normally, and the pressure and gravity of the planet are, luckily, similar to Earth. The spheres are bobbing up and down, happy that you are evidently able to survive their planet. 

The spheres begin to glide away from the spaceship in a northerly direction (from the spacecraft—to clarify, if a compass rose were put on top of the spacecraft, North would be pointing the direction in which you are heading, but that’s not necessarily the accurate cardinal direction). You follow them because a) it would not be pleasant to be stuck on an unknown planet alone and b) you want to see where they’re going. The spheres have been fairly benevolent so far, so you don’t think they’d lead you to harm.

The spheres keep gliding along and after about ten minutes you glance back to see the spacecraft in the distance, slowly disappearing behind the horizon. 

The spheres keep going. After about twenty minutes, the spacecraft disappears completely. You follow them some more. You follow the spheres for what seems to be hours. 

The seconds stretch to minutes, the minutes to hours, the hours to days, the days to weeks, the weeks to months, the months to years, the years to centuries, the centuries to æons, until you have absolutely exhausted your hyperbolic license. Still, you keep walking, untiring.

The spacecraft you arrived in has long since disappeared behind the horizon of this small, barren planet. You haven’t seen a single landmark by which to find your way back to the spaceship if anything goes wrong, which it probably won’t. Why would it? You are clearly perfectly safe here on this planet of barren wastes and three spherical creatures that you can barely communicate with. 

You look down at your arm to check the time, but then you realize that you aren’t wearing your watch, which your third-favorite uncle left to you when he died. (You never told him he was only your third-favorite.) You left it at home because it turns out that plastic (or at least, that specific breed) is not good at being a watch, especially as all of the fragile mechanical parts have to be made of plastic. It worked for a while and then broke as you were attempting to sauté some chicken nuggets. You think that the flipping motion of your wrist must have knocked free some infinitesimally tiny gear in the plastic machine, but you never actually bothered to get it fixed because you never really relished the idea of walking around with a bright orange plastic watch on your wrist, anyways. But, staring at your arm, you think your skin has taken on a slight grey tinge. It’s probably just the helmet filtering your vision, so you pay it no heed.

The spheres keep going. You’re sure that you must have walked at least one billion miles by now. The spheres never seem to get tired or distracted, so you just follow them because what else is there to do? If you stop, they’d probably just leave you there, and you’d starve. Well, you would die of dehydration first, but that doesn’t really matter because you’re not going to stop and let them leave you behind. 

You look down at the ground to see if there’s any bugs, spiders, plant life, or any life, really (besides the spheres of course) on this barren planet. You don’t see anything, but you do notice that your feet seem to have risen off the ground. You aren’t any taller than normal, but your legs seem to have scrunched into themselves, rising off the ground but otherwise causing no damage as far as you can see. As you had been, up to this point, staring pretty much straight ahead of you, you hadn’t noticed your legs’ slow shrinking. Mysterious that you hadn’t felt it (you don’t feel anything now either), and you now seem to be walking on the air as if it is the ground but made of air, but the ground. But it doesn’t seem to be harming you and you can’t do anything about it, so you just keep walking.



After what may have been hours or days (you’re losing your sense of time- every second is the same eternal plodding, and the whole sky is covered in clouds that never darken) all of your legs are gone without a trace. However, you are still able to bob along, so you do that. You don’t want to get left behind. 

Your arms go next, gradually. You barely notice that they’re gone. You really weren’t using them, anyways. Who needs arms, really? You can just bump into stuff with your face. But before they’re gone, you notice that they are distinctly grey—the same shade of grey as the spheres. Curious.

After your arms, your torso leaves you too, until you’re just a helmet, bobbing in midair. You wonder if your face is the same shade of grey as your arms were before they left you. You continue to bob along with the spheres. 

After an extended period of time filled with endless journeying, (you’ve stopped trying to count the time) you decide that this has gone on long enough. You try to talk to the spheres, or at least make some noises that could alert you to your emotional distress, but you can’t. All that you can do is make vague yelps. Your mouth is gone. Your eyes, nose, ears—vanished. You can still see, and think, but you can’t talk. You’re now just a sphere, bobbing in the air. You’ve become one of them. 

The spacecraft appears around the horizon, and you understand, now. You enter with the other spheres. You know what you have to do.

x

