# Section 58 {#sec-58}

You decide to stop screaming. Even though you have deduced that the spheres’ main form of communication is through screams, you can’t tell what you’re saying to them and don’t want to accidentally say something offensive or angering. 

Your screams cease, and so do the spheres’ guttural shrieks and yelps. Then, one of them bobs smoothly through the air towards you. That sphere begins a series of small shrieks that end in a higher-pitched tone. If this follows the same language patterns as English, this monochrome orb (you idly wonder why everything about these spheres is in varying shades of black, white, and grey. Perhaps they can’t see in color. Perhaps they don’t even know what color is and don’t miss it, their vision being akin to having cameras strapped to your head filming in black-and-white and then watching that film in real time through a television strapped to your eyes, plus depth perception, with the lag subtracted. Perhaps they just have a vague outline of the world because they have no eyes, perceiving it through echolocation or something alike, having no idea of the subtleties and shades of the deepest blues and brightest yellows, feeling a nameless, inexplicable melancholy at random points in the day for the loss of them. Perhaps it’s just a stylistic choice. The world may never know) is asking you a question!

You don’t know what the question is, but perhaps if you display your confusion, they will clarify. However, there’s still the pressing matter of your very important event and, since the spheres haven’t yet shown any intent on harming you, you might just back away, and they would possibly understand your intent and set you free.

If you try to get them to clarify, turn to @sec-26. 

If you back away, turn to @sec-04.
