# Section 64 {#sec-64}

You rear back, your gut still aching. Anger courses through your arteries and your fist flies out and catches him in the jaw. He flies backwards from the force of your blow and lands hard—too hard—on the concrete with a haunting, final-sounding crack. Blood begins to pool about his head like a strange, macabre halo. His breath catches, he gasps in a terrible rattle. You stand there in shock, staring. All the anger has ebbed out of your body and been replaced with a hollow surprise. 

He lies upon the ground like a puppet whose strings have been severed, devoid of animation. His eyes are open but unseeing. You step towards—what? It? Him? The Corpse? —and reach out a trembling hand to feel for a pulse. You touch his (you’ve decided to pretend that he’s not dead) neck gently, at the jugular where the pulse is strongest—should be strongest. Nothing. You press harder. Still nothing. You stand back, feeling strangely calm. Then the startling realization filters through your skull—you’ve just killed a man. You start to panic. Do you run from the law? Claim it was an accident? Blame someone else? Turn yourself in? Lie on the ground and panic but not actually do anything? 

By default, you decide on the last one and in a few hours a police officer comes by on his patrol. He regards you on the floor and then barks something indecipherable into his radio.

You are soon ushered into his police car, which he seems to have left on the curb before walking around to where you were, but you show no resistance. You don’t really see the point. They’d catch and arrest you anyway; your chances of escape have flown out the window like an uninjured bird. 

You wonder vaguely how he knew to find you there. And the corpse. The corpse is loaded into the back of the car, and you set off towards the police station. You are set in an interrogation room and, with nothing else to do, you tell the truth. What else can you do? You don’t really register the processes of the police and the court, but you do recall being given the right to hire a lawyer. But should you? You might be able to defend yourself. 

If you hire a lawyer, turn to @sec-39.

If you decide that you can defend yourself in court, turn to @sec-35.
 
