# Section 65 {#sec-65}

You decide to request to be turned into an onion.

“Make me an onion!” you say to the extremely large octopus. 

“Certainly!” it says, and waves a tentacle, sending a foul-smelling ray of light washing across the room. “Bzzzt! You’re an onion!” 

You look down and realize that you are in fact an onion! Your hands and feet are gone, but you don’t really miss them. You’re an onion now, and can easily roll around to get from A to B.

You roll around the cavern for a while, getting your bearings and acclimating yourself to the fact that you are an onion. “Wheeeeee! I’m an onion!” you say, because you are an onion, and apparently one with the ability to speak.

After you are finished exploring the floor of the cavern, you sit on the rock for a minute. How are you going to leave? There’s a ladder leading up to the little door, and though rolling around is an efficient mode of transportation, it’s not ideal for climbing up ladders.

“One more request—could you lift me up to that little doorway up there?” you ask the octopus. 
“Why, of course!” it says, and, grabbing you by the stem, sets you down on the ground just outside of the little doorway. “Thank you!” you shout to it and hear a faint Of course as you roll away through a swaying field of grass. 


After traveling through the field for hours, you come across a path and, with nothing else to do, you follow it. As you roll along the path, your mind wanders. How are you able to see with no eyes, hear with no ears, and speak with no mouth? Can all onions do this? Are they all sentient? Should you have apologized to the onions you’ve eaten in your life? 

As you ponder these things, you stop paying attention to the path in front of you, and within minutes bump into something. It’s shiny, smooth, a light coffee color, and in your way. You back up and bump into it again, hoping to convince it to move. “Move,” you say. “I have places to go! Well, really I’m not going anywhere in particular, but I’d like to get there in a timely manner, so could you kindly step aside?”

“An onion,” says a low, stupid-sounding voice. “An onion has bumped into my boot. What luck!” A large, fleshy hand picks you up and brings you level to a large, fleshy face. “Hello there. You’ll be just the thing for lunch. I do love a good onion soup.” 

“No!” you scream. “No, no, no!” Sadly, your pleas are in vain.

x
