project:
  type: book

book:
  title: "daylight-savings-time"
  author: "Norah Jones"
  date: "9/14/2024"
  chapters:
    - index.qmd
    - 01.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



