project:
  type: book

book:
  title: "Daylight Savings Time"
  author: "Beatrice McPherson"
  date: "9/14/2024"
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
    - 17.qmd
    - 18.qmd
    - 19.qmd
    - 20.qmd
    - 21.qmd
    - 22.qmd
    - 23.qmd
    - 24.qmd
    - 25.qmd
    - 26.qmd
    - 27.qmd
    - 28.qmd
    - 29.qmd
    - 30.qmd
    - 31.qmd
    - 32.qmd
    - 33.qmd
    - 34.qmd
    - 35.qmd
    - 36.qmd
    - 37.qmd
    - 38.qmd
    - 39.qmd
    - 40.qmd
    - 41.qmd
    - 42.qmd
    - 43.qmd
    - 44.qmd
    - 45.qmd
    - 46.qmd
    - 47.qmd
    - 48.qmd
    - 49.qmd
    - 50.qmd
    - 51.qmd
    - 52.qmd
    - 53.qmd
    - 54.qmd
    - 55.qmd
    - 56.qmd
    - 57.qmd
    - 58.qmd
    - 60.qmd
    - 61.qmd
    - 62.qmd
    - 63.qmd
    - 64.qmd
    - 65.qmd
    - 66.qmd
    - 67.qmd
    - hair-carp.qmd
  sidebar: false
  navbar: false

format:
  html:
    theme: litera
    number-sections: false
  pdf:
    documentclass: scrreprt
  epub:
    number-sections: false
    creator: "Beatrice McPherson"
    contributor: "Jonathan McPherson"


