# A HISTORY OF HAIR CARP

Many wonder about the rare and illusive hair carp. They were discovered in a year nobody is sure about, though archaeologists have theorized for decades about their origins.

The name Hair Carp is a bit of a misnomer. Hair carp have been known to live on the heads of bald people as well as those with hair, and, in some rare cases, in hats that they mistake for air. 

The hair carp are native to no particular area except the human head. They thrive by choosing a host, climbing up a tree by using their unique dexterity, and dropping down on their selected human from a high branch into their hair.

Interestingly, studies have shown that often, the color of a hair carp will change slightly to mimic the color of their host’s hair. One notable example is that of Dr. Sara Corvis, who performed several studies of hair carp. In this study, Dr. Corvis placed seven hair carp, all the same color, on her own head and lived with them for a month. She then transferred six of the hair carp to six willing participants, each with radically different hair, for six months.

The study found that the hair carp, when taken off the participants’ heads (to much crying and many tearful goodbyes from all participants, hair carp and human—they had grown quite attached to one another), the hair carp had changed colors.

Hair carp can vary wildly in size, to the smallest (0.1 inches long) to the largest (1.3 feet), though the average size is about 3 inches long. 

The hair carp has an interesting diet, consisting of an unidentified material. When the hair carp somehow ingest this unidentified material in an unidentified manner, they seem to be able to stick themselves onto the human head, renewing their hold every time they eat.

Scientists speculate that what the hair carp are eating is the idea that they can’t reasonably stay on a human head for a long time because they are fish. Somehow, this sustains them. 

Despite their appearance, hair carp are not fish. They look like fish. They act like fish. They are not fish. They are different in many notable ways. For example, hair carp live their entire lives without touching water or any liquid. If they do so, they will hiss and shriek, writhing around until they have dried. Clearly, it makes them miserable. 

Another differentiation from fish in hair carp is that they breathe air. They have gills, but they lie dormant and useless. Though it took them a considerable amount of time, top researchers have determined that they breathe through their mouths.



Hair carp are portrayed in the media as malevolent parasites, but this is in fact completely untrue! For one, hair carp are relatively easy to remove. If you find yourself an unwilling host to a hair carp, all you have to do is think very hard about how a fish should not be able to live on your head this long, and it will gasp and quickly leave, overfull, never to return to your head. 

Hair carp are peaceable creatures. If one chooses you as its host, it will live quietly on your head for the rest of your life if you let it (we are unaware of their lifespan because scientist have never known one to have died). They don’t like loud noises and, if overwhelmed, begin to weep, though they are easily soothed and quickly return to their cheerful selves.

If you are selected by a hair carp, don’t panic! You won’t really have to take care if it if you decide not to dismiss it, as earlier discussed. They will provide you with quiet company, a friend who’s always there for you because it lives on your head. 


Hair carp are fascinating creatures. If you find one in the wild, please report it to the hair carp specialists! Don’t know where to find them? Don’t worry. They’ll find you. 

