---
title: "I"
---

You turn over in bed and lazily glance at your alarm clock, taking in its display sleepily. Surely it can’t be time to get up yet- it’s still dark out! 

You peer closer at the alarm. You’ve slept in! Inwardly cursing your alarm clock for its unreliability, you hurry into your non-pajama clothes without even taking a minute to appreciate the wonders of daylight savings time.

As you are hurriedly (much too hurriedly- a dentist or anyone even slightly related to any orthodontic job would be horrified at you) brushing your teeth, you remember that event you’re supposed to attend today. It’s particularly important; it could decide the future of your life! You think anxiously back on your notes. Did you use that semicolon correctly? Then another, more pressing problem gives up on knocking and lets itself into your—admittedly rather small—brain (rather rudely, however there are extenuating circumstances): dubious semicolon aside, are you even going to be there to read said notes? You’re going to be late! 

You slap together a mustard, mayonnaise, and pickle sandwich on pumpernickel & rye (one slice of bread is pumpernickel and the other is rye), which has always been your favorite.

 You’re just about ready to step out the door when you realize that you’re not wearing shoes! You stare down at your bare toes as indecision grips you in an unpleasantly firm fist. Which shoes to wear‽ You stare down in paralysis at the two pairs of shoes on the rack. One is your comfortable, worn in, favorite shoes. The other is your dress shoes- they haven’t seen much use. 

If you decide to wear the comfortable shoes, turn to @sec-14.

If you decide to wear the dress shoes, turn to @sec-15.

If you just give up and go barefoot, turn to @sec-66.
